/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as CancelStreamScriptJson } from "../scripts/CancelStream.ral.json";
import { default as CreateCustomStreamScriptJson } from "../scripts/CreateCustomStream.ral.json";
import { default as CreateLinearStreamScriptJson } from "../scripts/CreateLinearStream.ral.json";
import { default as UnlockStreamScriptJson } from "../scripts/UnlockStream.ral.json";
import { StreamConfig, AllStructs } from "./types";

export const CancelStream = new ExecutableScript<{
  factory: HexString;
  id: bigint;
}>(Script.fromJson(CancelStreamScriptJson, "", AllStructs));

export const CreateCustomStream = new ExecutableScript<{
  factory: HexString;
  tokenId: HexString;
  amount: bigint;
  recipient: Address;
  isCancelable: boolean;
  startTimestamp: bigint;
  unlockInterval: bigint;
  unlockPercentage: bigint;
}>(Script.fromJson(CreateCustomStreamScriptJson, "", AllStructs));

export const CreateLinearStream = new ExecutableScript<{
  factory: HexString;
  tokenId: HexString;
  amount: bigint;
  recipient: Address;
  isCancelable: boolean;
  startTimestamp: bigint;
  endTimestamp: bigint;
}>(Script.fromJson(CreateLinearStreamScriptJson, "", AllStructs));

export const UnlockStream = new ExecutableScript<{
  factory: HexString;
  id: bigint;
  amount: bigint;
}>(Script.fromJson(UnlockStreamScriptJson, "", AllStructs));
