/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as StreamContractJson } from "../Stream.ral.json";
import { getContractByCodeHash } from "./contracts";
import { StreamConfig, AllStructs } from "./types";

// Custom types for the contract
export namespace StreamTypes {
  export type Fields = {
    factoryContractId: HexString;
    creator: Address;
    recipient: Address;
    tokenId: HexString;
    amount: bigint;
    config: StreamConfig;
    withdrawnAmount: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getStreamDetails: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[Address, Address, HexString, StreamConfig]>;
    };
    getLockedAmount: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAvailableAmount: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    addWithdrawnAmount: {
      params: CallContractParams<{ value: bigint }>;
      result: CallContractResult<null>;
    };
    transferStream: {
      params: CallContractParams<{ address: Address }>;
      result: CallContractResult<null>;
    };
    destroyStream: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    getStreamDetails: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getLockedAmount: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAvailableAmount: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    addWithdrawnAmount: {
      params: SignExecuteContractMethodParams<{ value: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    transferStream: {
      params: SignExecuteContractMethodParams<{ address: Address }>;
      result: SignExecuteScriptTxResult;
    };
    destroyStream: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<StreamInstance, StreamTypes.Fields> {
  encodeFields(fields: StreamTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as StreamTypes.Fields;
  }

  consts = {
    StreamError: { UnknownKind: BigInt("0"), NotAuthorized: BigInt("1") },
  };

  at(address: string): StreamInstance {
    return new StreamInstance(address);
  }

  tests = {
    getStreamDetails: async (
      params: Omit<
        TestContractParamsWithoutMaps<StreamTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<
      TestContractResultWithoutMaps<[Address, Address, HexString, StreamConfig]>
    > => {
      return testMethod(
        this,
        "getStreamDetails",
        params,
        getContractByCodeHash
      );
    },
    getLockedAmount: async (
      params: Omit<
        TestContractParamsWithoutMaps<StreamTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getLockedAmount", params, getContractByCodeHash);
    },
    getAvailableAmount: async (
      params: Omit<
        TestContractParamsWithoutMaps<StreamTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getAvailableAmount",
        params,
        getContractByCodeHash
      );
    },
    addWithdrawnAmount: async (
      params: TestContractParamsWithoutMaps<
        StreamTypes.Fields,
        { value: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "addWithdrawnAmount",
        params,
        getContractByCodeHash
      );
    },
    transferStream: async (
      params: TestContractParamsWithoutMaps<
        StreamTypes.Fields,
        { address: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "transferStream", params, getContractByCodeHash);
    },
    destroyStream: async (
      params: Omit<
        TestContractParamsWithoutMaps<StreamTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroyStream", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const Stream = new Factory(
  Contract.fromJson(
    StreamContractJson,
    "",
    "fb927c8b00a2206a0dfb15dd912c9c759d4a1deaad08a909f5249a97413c615d",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class StreamInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<StreamTypes.State> {
    return fetchContractState(Stream, this);
  }

  view = {
    getStreamDetails: async (
      params?: StreamTypes.CallMethodParams<"getStreamDetails">
    ): Promise<StreamTypes.CallMethodResult<"getStreamDetails">> => {
      return callMethod(
        Stream,
        this,
        "getStreamDetails",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getLockedAmount: async (
      params?: StreamTypes.CallMethodParams<"getLockedAmount">
    ): Promise<StreamTypes.CallMethodResult<"getLockedAmount">> => {
      return callMethod(
        Stream,
        this,
        "getLockedAmount",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAvailableAmount: async (
      params?: StreamTypes.CallMethodParams<"getAvailableAmount">
    ): Promise<StreamTypes.CallMethodResult<"getAvailableAmount">> => {
      return callMethod(
        Stream,
        this,
        "getAvailableAmount",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    addWithdrawnAmount: async (
      params: StreamTypes.CallMethodParams<"addWithdrawnAmount">
    ): Promise<StreamTypes.CallMethodResult<"addWithdrawnAmount">> => {
      return callMethod(
        Stream,
        this,
        "addWithdrawnAmount",
        params,
        getContractByCodeHash
      );
    },
    transferStream: async (
      params: StreamTypes.CallMethodParams<"transferStream">
    ): Promise<StreamTypes.CallMethodResult<"transferStream">> => {
      return callMethod(
        Stream,
        this,
        "transferStream",
        params,
        getContractByCodeHash
      );
    },
    destroyStream: async (
      params?: StreamTypes.CallMethodParams<"destroyStream">
    ): Promise<StreamTypes.CallMethodResult<"destroyStream">> => {
      return callMethod(
        Stream,
        this,
        "destroyStream",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getStreamDetails: async (
      params: StreamTypes.SignExecuteMethodParams<"getStreamDetails">
    ): Promise<StreamTypes.SignExecuteMethodResult<"getStreamDetails">> => {
      return signExecuteMethod(Stream, this, "getStreamDetails", params);
    },
    getLockedAmount: async (
      params: StreamTypes.SignExecuteMethodParams<"getLockedAmount">
    ): Promise<StreamTypes.SignExecuteMethodResult<"getLockedAmount">> => {
      return signExecuteMethod(Stream, this, "getLockedAmount", params);
    },
    getAvailableAmount: async (
      params: StreamTypes.SignExecuteMethodParams<"getAvailableAmount">
    ): Promise<StreamTypes.SignExecuteMethodResult<"getAvailableAmount">> => {
      return signExecuteMethod(Stream, this, "getAvailableAmount", params);
    },
    addWithdrawnAmount: async (
      params: StreamTypes.SignExecuteMethodParams<"addWithdrawnAmount">
    ): Promise<StreamTypes.SignExecuteMethodResult<"addWithdrawnAmount">> => {
      return signExecuteMethod(Stream, this, "addWithdrawnAmount", params);
    },
    transferStream: async (
      params: StreamTypes.SignExecuteMethodParams<"transferStream">
    ): Promise<StreamTypes.SignExecuteMethodResult<"transferStream">> => {
      return signExecuteMethod(Stream, this, "transferStream", params);
    },
    destroyStream: async (
      params: StreamTypes.SignExecuteMethodParams<"destroyStream">
    ): Promise<StreamTypes.SignExecuteMethodResult<"destroyStream">> => {
      return signExecuteMethod(Stream, this, "destroyStream", params);
    },
  };

  async multicall<Calls extends StreamTypes.MultiCallParams>(
    calls: Calls
  ): Promise<StreamTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Stream,
      this,
      calls,
      getContractByCodeHash
    )) as StreamTypes.MultiCallResults<Calls>;
  }
}
