/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as StreamFactoryContractJson } from "../StreamFactory.ral.json";
import { getContractByCodeHash } from "./contracts";
import { StreamConfig, AllStructs } from "./types";

// Custom types for the contract
export namespace StreamFactoryTypes {
  export type Fields = {
    streamTemplateId: HexString;
    vaultTemplateId: HexString;
    streamCounter: bigint;
  };

  export type State = ContractState<Fields>;

  export type StreamCreatedEvent = ContractEvent<{
    streamId: bigint;
    creator: Address;
    recipient: Address;
    contractId: HexString;
  }>;
  export type StreamWithdrawnEvent = ContractEvent<{
    streamId: bigint;
    recipient: Address;
    tokenId: HexString;
    amount: bigint;
  }>;
  export type StreamCanceledEvent = ContractEvent<{
    streamId: bigint;
    creator: Address;
    tokenId: HexString;
    amount: bigint;
  }>;
  export type StreamTransferredEvent = ContractEvent<{
    streamId: bigint;
    recipient: Address;
  }>;

  export interface CallMethodTable {
    createVault: {
      params: CallContractParams<{ tokenId: HexString }>;
      result: CallContractResult<HexString>;
    };
    createStream: {
      params: CallContractParams<{
        caller: Address;
        tokenId: HexString;
        amount: bigint;
        recipient: Address;
        config: StreamConfig;
      }>;
      result: CallContractResult<null>;
    };
    withdrawStream: {
      params: CallContractParams<{ streamId: bigint; amount: bigint }>;
      result: CallContractResult<null>;
    };
    transferStream: {
      params: CallContractParams<{ streamId: bigint; newRecipient: Address }>;
      result: CallContractResult<null>;
    };
    cancelStream: {
      params: CallContractParams<{ streamId: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    createVault: {
      params: SignExecuteContractMethodParams<{ tokenId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    createStream: {
      params: SignExecuteContractMethodParams<{
        caller: Address;
        tokenId: HexString;
        amount: bigint;
        recipient: Address;
        config: StreamConfig;
      }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawStream: {
      params: SignExecuteContractMethodParams<{
        streamId: bigint;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    transferStream: {
      params: SignExecuteContractMethodParams<{
        streamId: bigint;
        newRecipient: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    cancelStream: {
      params: SignExecuteContractMethodParams<{ streamId: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  StreamFactoryInstance,
  StreamFactoryTypes.Fields
> {
  encodeFields(fields: StreamFactoryTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as StreamFactoryTypes.Fields;
  }

  eventIndex = {
    StreamCreated: 0,
    StreamWithdrawn: 1,
    StreamCanceled: 2,
    StreamTransferred: 3,
  };
  consts = {
    StreamFactoryError: {
      NotAuthorized: BigInt("0"),
      NotAvailable: BigInt("1"),
      NotCancelable: BigInt("2"),
      NotTransferable: BigInt("3"),
      InvalidAmount: BigInt("4"),
      InvalidStreamPeriod: BigInt("5"),
      InvalidUnlockInterval: BigInt("6"),
      InvalidUnlockPercentage: BigInt("7"),
      InvalidUnlockStepsLength: BigInt("8"),
      InvalidUnlockStepsOrder: BigInt("9"),
      InvalidWithdrawAmount: BigInt("10"),
      VaultAlreadyExists: BigInt("11"),
      VaultDoesNotExist: BigInt("12"),
    },
  };

  at(address: string): StreamFactoryInstance {
    return new StreamFactoryInstance(address);
  }

  tests = {
    createVault: async (
      params: TestContractParamsWithoutMaps<
        StreamFactoryTypes.Fields,
        { tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "createVault", params, getContractByCodeHash);
    },
    createStream: async (
      params: TestContractParamsWithoutMaps<
        StreamFactoryTypes.Fields,
        {
          caller: Address;
          tokenId: HexString;
          amount: bigint;
          recipient: Address;
          config: StreamConfig;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createStream", params, getContractByCodeHash);
    },
    withdrawStream: async (
      params: TestContractParamsWithoutMaps<
        StreamFactoryTypes.Fields,
        { streamId: bigint; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawStream", params, getContractByCodeHash);
    },
    transferStream: async (
      params: TestContractParamsWithoutMaps<
        StreamFactoryTypes.Fields,
        { streamId: bigint; newRecipient: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "transferStream", params, getContractByCodeHash);
    },
    cancelStream: async (
      params: TestContractParamsWithoutMaps<
        StreamFactoryTypes.Fields,
        { streamId: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "cancelStream", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const StreamFactory = new Factory(
  Contract.fromJson(
    StreamFactoryContractJson,
    "=10-2+8f=2-2+32=2-2+7b=2-2+fc=135-1+7=562+a00016187e030a53747265616d204964200f202d20436f6e74726163742049642000=762",
    "28b434f6d8068a313b3d2c479de9e06280b789f30e3af7dd22c62791763d6219",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class StreamFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<StreamFactoryTypes.State> {
    return fetchContractState(StreamFactory, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeStreamCreatedEvent(
    options: EventSubscribeOptions<StreamFactoryTypes.StreamCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      StreamFactory.contract,
      this,
      options,
      "StreamCreated",
      fromCount
    );
  }

  subscribeStreamWithdrawnEvent(
    options: EventSubscribeOptions<StreamFactoryTypes.StreamWithdrawnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      StreamFactory.contract,
      this,
      options,
      "StreamWithdrawn",
      fromCount
    );
  }

  subscribeStreamCanceledEvent(
    options: EventSubscribeOptions<StreamFactoryTypes.StreamCanceledEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      StreamFactory.contract,
      this,
      options,
      "StreamCanceled",
      fromCount
    );
  }

  subscribeStreamTransferredEvent(
    options: EventSubscribeOptions<StreamFactoryTypes.StreamTransferredEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      StreamFactory.contract,
      this,
      options,
      "StreamTransferred",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | StreamFactoryTypes.StreamCreatedEvent
      | StreamFactoryTypes.StreamWithdrawnEvent
      | StreamFactoryTypes.StreamCanceledEvent
      | StreamFactoryTypes.StreamTransferredEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      StreamFactory.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    createVault: async (
      params: StreamFactoryTypes.CallMethodParams<"createVault">
    ): Promise<StreamFactoryTypes.CallMethodResult<"createVault">> => {
      return callMethod(
        StreamFactory,
        this,
        "createVault",
        params,
        getContractByCodeHash
      );
    },
    createStream: async (
      params: StreamFactoryTypes.CallMethodParams<"createStream">
    ): Promise<StreamFactoryTypes.CallMethodResult<"createStream">> => {
      return callMethod(
        StreamFactory,
        this,
        "createStream",
        params,
        getContractByCodeHash
      );
    },
    withdrawStream: async (
      params: StreamFactoryTypes.CallMethodParams<"withdrawStream">
    ): Promise<StreamFactoryTypes.CallMethodResult<"withdrawStream">> => {
      return callMethod(
        StreamFactory,
        this,
        "withdrawStream",
        params,
        getContractByCodeHash
      );
    },
    transferStream: async (
      params: StreamFactoryTypes.CallMethodParams<"transferStream">
    ): Promise<StreamFactoryTypes.CallMethodResult<"transferStream">> => {
      return callMethod(
        StreamFactory,
        this,
        "transferStream",
        params,
        getContractByCodeHash
      );
    },
    cancelStream: async (
      params: StreamFactoryTypes.CallMethodParams<"cancelStream">
    ): Promise<StreamFactoryTypes.CallMethodResult<"cancelStream">> => {
      return callMethod(
        StreamFactory,
        this,
        "cancelStream",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createVault: async (
      params: StreamFactoryTypes.SignExecuteMethodParams<"createVault">
    ): Promise<StreamFactoryTypes.SignExecuteMethodResult<"createVault">> => {
      return signExecuteMethod(StreamFactory, this, "createVault", params);
    },
    createStream: async (
      params: StreamFactoryTypes.SignExecuteMethodParams<"createStream">
    ): Promise<StreamFactoryTypes.SignExecuteMethodResult<"createStream">> => {
      return signExecuteMethod(StreamFactory, this, "createStream", params);
    },
    withdrawStream: async (
      params: StreamFactoryTypes.SignExecuteMethodParams<"withdrawStream">
    ): Promise<
      StreamFactoryTypes.SignExecuteMethodResult<"withdrawStream">
    > => {
      return signExecuteMethod(StreamFactory, this, "withdrawStream", params);
    },
    transferStream: async (
      params: StreamFactoryTypes.SignExecuteMethodParams<"transferStream">
    ): Promise<
      StreamFactoryTypes.SignExecuteMethodResult<"transferStream">
    > => {
      return signExecuteMethod(StreamFactory, this, "transferStream", params);
    },
    cancelStream: async (
      params: StreamFactoryTypes.SignExecuteMethodParams<"cancelStream">
    ): Promise<StreamFactoryTypes.SignExecuteMethodResult<"cancelStream">> => {
      return signExecuteMethod(StreamFactory, this, "cancelStream", params);
    },
  };

  async multicall<Calls extends StreamFactoryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<StreamFactoryTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      StreamFactory,
      this,
      calls,
      getContractByCodeHash
    )) as StreamFactoryTypes.MultiCallResults<Calls>;
  }
}
